name: coronavirus_covid-19
channels:
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - jupyter_contrib_nbextensions
  - autopep8
  - beautifulsoup4
  - requests
  - pandas
  - geopandas
  - matplotlib
  - pillow
  - xlrd
  - descartes

